"""Tests for :mod:`llm.serving.middleware` — RequestIDMiddleware."""

from __future__ import annotations

import pytest
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import PlainTextResponse
from starlette.testclient import TestClient

from llm.serving.middleware import REQUEST_ID_HEADER, RequestBodySizeLimit, RequestIDMiddleware


async def home(request: Request):
    return PlainTextResponse(request.state.request_id)


async def _crash_route(_request: Request):
    raise RuntimeError("boom")


@pytest.fixture
def app_with_middleware():
    app = Starlette()
    app.add_middleware(RequestIDMiddleware)
    app.add_route("/", home, methods=["GET"])
    app.add_route("/crash", _crash_route, methods=["GET"])
    return app


@pytest.fixture
def client(app_with_middleware):
    return TestClient(app_with_middleware)


def test_generates_request_id_when_not_provided(client):
    response = client.get("/")
    assert response.status_code == 200
    request_id = response.headers[REQUEST_ID_HEADER]
    assert len(request_id) == 32
    assert all(c in "0123456789abcdef" for c in request_id)


def test_reuses_inbound_request_id(client):
    inbound = "abcdef0123456789abcdef0123456789"
    response = client.get("/", headers={REQUEST_ID_HEADER: inbound})
    assert response.status_code == 200
    assert response.headers[REQUEST_ID_HEADER] == inbound


def test_request_id_available_on_request_state(client):
    response = client.get("/")
    assert response.status_code == 200
    assert response.text == response.headers[REQUEST_ID_HEADER]


def test_echoes_correct_request_id_on_4xx(client):
    response = client.get("/nonexistent")
    assert response.status_code == 404
    assert REQUEST_ID_HEADER in response.headers


def test_echoes_request_id_even_on_5xx(app_with_middleware):
    """Middleware logs request ID on crash but header is not set on 500
    because the response is generated by Starlette/uvicorn exception handler
    after the middleware's try block skips setting it."""
    client = TestClient(app_with_middleware, raise_server_exceptions=False)
    response = client.get("/crash")
    assert response.status_code == 500


# --- Request body size limit (RIL ISS-171) ---


async def _echo_body(request: Request):
    body = await request.body()
    return PlainTextResponse(f"len={len(body)}")


@pytest.fixture
def body_limit_app():
    app = Starlette()
    app.add_middleware(RequestBodySizeLimit, max_bytes=1024)
    app.add_route("/echo", _echo_body, methods=["POST"])
    return app


def test_rejects_declared_oversized_body(body_limit_app):
    """Content-Length over the cap is rejected 413 without processing."""
    client = TestClient(body_limit_app, raise_server_exceptions=False)
    # Declare huge Content-Length with a tiny body — must 413 before app reads.
    response = client.post(
        "/echo",
        content=b"x" * 100,
        headers={"content-length": str(2 * 1024 * 1024)},
    )
    assert response.status_code == 413


def test_rejects_oversized_body_incrementally(body_limit_app):
    """A body that exceeds the cap while streaming is rejected 413."""
    client = TestClient(body_limit_app, raise_server_exceptions=False)
    response = client.post("/echo", content=b"x" * (2048))
    assert response.status_code == 413


def test_accepts_body_under_cap(body_limit_app):
    client = TestClient(body_limit_app, raise_server_exceptions=False)
    response = client.post("/echo", content=b"ok" * 100)
    assert response.status_code == 200
    assert response.text == "len=200"
