name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up UV Environment
                uses: astral-sh/setup-uv@v6

            -   name: Synchronize Dependencies for Linting
                run: uv sync --quiet

            -   name: Check Code Formatting
                run: uvx ruff format --check .

            -   name: Lint Code
                run: uvx ruff check .

    build-and-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
            fail-fast: false

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up UV Environment
                uses: astral-sh/setup-uv@v6

            -   name: Synchronize Dependencies
                run: uv sync

            -   name: Build Project
                run: uvx hatch build

            -   name: Run Pytest Tests
                run: uv run pytest --cov=src/llm --cov-report=xml

            -   name: Upload coverage report as artifact
                if: always() # Ensure it runs even if tests fail, to upload partial coverage
                uses: actions/upload-artifact@v4
                with:
                    name: coverage-report-${{ matrix.os }} # Make artifact name unique per OS
                    path: coverage.xml
